### ISSUE TITLE
Two and done

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#36] opened 2021-12-08 19:04 UTC
I've been holding off reporting this one because I can't figure out what the cause is.  But I gave up.  What's happening is occasionally the tool only downloads two jpgs, then goes on to the next one.  The CBZ file is just two pages long.  Here is a screenshot where it happened twice.
![image](https://user-images.githubusercontent.com/20542548/145267119-75961e5f-960c-411a-ae68-6d43fc43b6f8.png)

In the folders, it is just the two jpgs.
![image](https://user-images.githubusercontent.com/20542548/145267273-9d98823a-c5ad-4262-aa34-c13329c47348.png)

This comic is actually 35 pages.  

It doesn't happen all the time and it never seems to happen twice on the same comic.  I can't figure out a pattern to it.

**Comment by magnuschase293** [comment] 2021-12-08 19:59
It will certainly be a challenge to figure out the cause of such an elusive bug. Right now I can only think that the problem lies in the way the script figures out a comic is fully loaded. Particularly, in line 219 of RCO_links. (See photo below.) 

![Screenshot_2021-12-08-16-31-50-517_com.github.android.jpg](https://user-images.githubusercontent.com/65515378/145272190-29a5cea4-925f-40b1-9dec-87dd20666e7c.jpg)

It forces the driver to wait till the image loading animation in readcomiconline finishes. Perhaps, there is an instant where no image is loading in this particular issues you mention and they are later resumed.

The reasons for this might be os or internet dependent, but I will do my best to replicate it.

I will look into it as soon as I can. Meanwhile try inserting the following line of code between lines 218 and 219:
`driver.execute_script("window.scrollTo(0,document.body.scrollHeight;")`.

**Comment by StrangeDOS** [comment] 2021-12-08 20:43
I put it in the RCO_links.py file.  I'll give that a shot.  I already put a section in my sorting script to catch any instances of it happening again.  I should know pretty quickly if it works. 
I'll let you know what happens.

**Comment by StrangeDOS** [comment] 2021-12-08 21:59
Doesn't work.  Just sits here and spins....
![image](https://user-images.githubusercontent.com/20542548/145291188-e30164b0-e607-44d4-beb8-2f733ba1a7fd.png)

**Comment by magnuschase293** [comment] 2021-12-09 03:00
Oops, my bad a closing parenthesis was missing. Here is the right line: `driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")`. By the way I can confirm that I couldn't reproduce the error in MacOS and was able to download Heartbeat at once.

**Comment by magnuschase293** [comment] 2021-12-09 03:16
> Doesn't work. Just sits here and spins.... ![image](https://user-images.githubusercontent.com/20542548/145291188-e30164b0-e607-44d4-beb8-2f733ba1a7fd.png)
In order to save you some time, have in mind that whenever you see a Traceback message the program has stopped. Even if the loading animation is present the download will not finish due to a certain error and you can just terminate the program. 

I know this isn't a neat way to exit the script when an error occurs and is the result of lazyness on my behalf through the different versions. Perhaps a simple try-except will solve it I will look into it.

**Comment by StrangeDOS** [comment] 2021-12-09 03:18
Sorry, its not with a specific title.  That's just the one I did a screenshot of.  If I tried to download the same title again, it would most likely complete.  Its not happening to specific titles, its completely random.  For a test, I downloaded a bunch of titles a second time after they had already failed once.  All of them downloaded fine on the second try.

**Comment by vengeance101** [comment] 2021-12-10 06:35
With a non-deterministic bug like this, it might be very hard to narrow down and fix. One alternative solution is putting in a basic validation step. Have the program determine how many pages it expects (or maybe just more than 2, if the error is always 2 pages alone), and then if the download doesn't match (or is only 2 pages), delete and force redownload.

**Comment by StrangeDOS** [comment] 2021-12-10 06:48
That's why I held off for a while before reporting the bug.  I wanted to be able to give you move information to go on, but it just seemed random.  And yes, when it happens, it is always 2 pages.

**Comment by magnuschase293** [comment] 2021-12-10 18:32
> With a non-deterministic bug like this, it might be very hard to narrow down and fix. One alternative solution is putting in a basic validation step. Have the program determine how many pages it expects (or maybe just more than 2, if the error is always 2 pages alone), and then if the download doesn't match (or is only 2 pages), delete and force redownload.

This is a good approach and should solve the bug, but perhaps scrolling down to the bottom of the page (that's what the line I asked @StrangeDOS to add in RCO_links does) is enough to solve the problem. Plesase, let me know if the bug happens again after inserting the line of code.

**Comment by StrangeDOS** [comment] 2021-12-11 18:04
The additional line in RCO_links.py has been working fine and I haven't seen ANY additional instances of downloading just the 2 pages.  I'd say this corrects the issue.

**Closed** 2021-12-21 19:28 UTC
